### ISSUE TITLE
in console /admin/artisan/json/ 404 (Not Found)

### ISSUE THREAD

**Issue by invaders-xx** [3x1io/filament-commands#1]
I installed the package with filament, did at php artisan optmize:clear and i get this error on the console when loading page:

http://blabla/admin/artisan/json/ 404 (Not Found)

**Comment by fadymondy** [comment]
i will fix it on the next update

**Comment by invaders-xx** [comment]
I still have the issue. Package updated, optimize:clear and console displays :
Failed to load resource: the server responded with a status of 404 ()

**Comment by fadymondy** [comment]
try 

```php
php artisan route:clear
```

**Comment by invaders-xx** [comment]
works fine now
