### ISSUE TITLE
Error on server

### ISSUE THREAD

**Issue by bitmicrosys** [3x1io/filament-commands#4]
I am getting the following error on server:

`Mixed Content: The page at 'https://example.com/admin/artisan' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://example.com/public/admin/artisan/json'. This request has been blocked; the content must be served over HTTPS.`

I solved it by adding in AppServiceProvider's boot() function:

```
Filament::pushMeta([
    new HtmlString('<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />'),
]);
```

**Comment by fadymondy** [comment]
it's because you are not using a secure connection with SSL. nice solutions for you is what you do

**Comment by bitmicrosys** [comment]
Actually I was using secure connection. Domain, Subdomains, Assets, all using secure connection with SSL. Even the app source was:  `<app home="https://mydomain.com" endpoint=https://mydomain.com/admin/artisan/json />` still got that error. I checked all the files and their sources, couldn't find any `http://` anywhere.
