### ISSUE TITLE
Not working with filament version 3

### ISSUE THREAD

**Issue by webappcoding** [3x1io/filament-commands#6]

**Comment by bernhardh** [comment]
Would be nice, if there is an upgrade

**Comment by martinedge** [comment]
Just need to change PluginServiceProvider to: 

use Spatie\LaravelPackageTools\PackageServiceProvider; 

and change the extends to PackageServiceProvider rather than PluginServiceProvider. 

See: https://filamentphp.com/docs/3.x/support/plugins/getting-started#upgrading-existing-plugins

**Comment by fadymondy** [comment]
this repo is closed for v2 to use v3 you can use this [repo](https://www.github.com/tomatophp/filament-artisan)
